# Generated by Django 5.2.4 on 2025-07-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='subscriber',
        ),
    ]
