# Generated by Django 5.2.4 on 2025-07-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_orders_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=510)),
                ('state', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
