# Generated by Django 5.2.4 on 2025-07-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cart_caritem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarItem',
            new_name='CartItem',
        ),
    ]
