# Generated by Django 5.2.4 on 2025-08-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_owner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
