# Generated by Django 5.2.4 on 2025-08-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_order_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_owner',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
    ]
