# Generated by Django 5.2.4 on 2025-08-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_order_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_owner',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
