# Generated by Django 5.2.4 on 2025-08-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_order_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='order_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10, null=True),
        ),
    ]
