# Generated by Django 5.2.4 on 2025-08-20 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_order_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
                ('variety', models.CharField(blank=True, max_length=50, null=True)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Sowing', 'Sowing'), ('Cultivation', 'Cultivation'), ('Harvest', 'Harvest'), ('Post-Harvest', 'Post-Harvest')], default='Planning', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Planning', 'Planning'), ('Sowing', 'Sowing'), ('Cultivation', 'Cultivation'), ('Harvest', 'Harvest'), ('Post-Harvest', 'Post-Harvest')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='home.crop')),
            ],
        ),
        migrations.CreateModel(
            name='CropActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_date', models.DateField()),
                ('details', models.TextField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='home.cropstage')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='home.farmer'),
        ),
    ]
