# Generated by Django 5.2.4 on 2025-08-23 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_crop_farmer_remove_cropstage_crop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('land_size', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=50)),
                ('water_source', models.CharField(choices=[(1, 'Tube well'), (2, 'canal'), (3, 'rain')], default=1)),
                ('temperature', models.CharField(max_length=50)),
                ('soil_moisture', models.CharField(max_length=50)),
                ('stage', models.IntegerField(choices=[(1, 'Crop Selection'), (2, 'Soil Preparation'), (3, 'Seed Growing'), (4, 'Irrigation & Fertilisation'), (5, 'Pest & Disease Control'), (6, 'Harvesting'), (7, 'Post-Harvesting')], default=1)),
                ('last_ai_advice', models.TextField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
