# Generated by Django 5.2.4 on 2025-08-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_cropplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropplan',
            old_name='stage',
            new_name='current_stage',
        ),
        migrations.AddField(
            model_name='cropplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
