# Generated by Django 5.2.4 on 2025-08-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_rename_stage_cropplan_current_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropplan',
            name='water_source',
            field=models.CharField(choices=[('Tube well', 'Tube well'), ('Canal', 'Canal'), ('Rain', 'Rain')], default='Tube well', max_length=20),
        ),
    ]
