# Generated by Django 5.2.4 on 2025-08-24 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_cropplan_water_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropplan',
            name='land_size',
        ),
        migrations.RemoveField(
            model_name='cropplan',
            name='soil_moisture',
        ),
        migrations.RemoveField(
            model_name='cropplan',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='cropplan',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='cropplan',
            name='water_source',
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_size', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=50)),
                ('water_source', models.CharField(choices=[('tube_well', 'Tube well'), ('canal', 'Canal'), ('rain', 'Rain')], default='tube_well', max_length=20)),
                ('temperature', models.CharField(max_length=50)),
                ('soil_moisture', models.CharField(max_length=50)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cropplan',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.farmerprofile'),
        ),
    ]
