# Generated by Django 5.2.4 on 2025-08-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_cropplan_land_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='land_size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
