# Generated by Django 5.2.4 on 2025-08-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_farmerprofile_land_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='soil_moisture',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='temperature',
        ),
    ]
