# Generated by Django 5.2.4 on 2025-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_farmerprofile_soil_moisture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='Agroecological_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
