# Generated by Django 5.2.4 on 2025-08-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_farmerprofile_agroecological_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropplan',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
