# Generated by Django 5.2.4 on 2025-08-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_cropplan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplan',
            name='harvesting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
