# Generated by Django 5.2.4 on 2025-08-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_cropplan_harvesting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplan',
            name='crop_variety',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
