# Generated by Django 5.2.4 on 2025-08-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_cropplan_crop_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
