# Generated by Django 5.2.4 on 2025-08-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_farmerprofile_lat_farmerprofile_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplan',
            name='crop_field',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
