# Generated by Django 5.2.4 on 2025-08-30 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_cropplan_crop_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '✅ Successfully Harvested'), ('damaged', '❌ Damaged / Failed')], max_length=20)),
                ('yield_amount', models.FloatField(blank=True, help_text='Yield in kilograms (or tons)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Remarks about outcome', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='home.cropplan')),
            ],
        ),
    ]
